### ISSUE TITLE
Can't load datanucleus on Wildfly 9.x

### ISSUE THREAD

**Issue by mottyc** [forcedotcom/java-sdk#33]
I'm using Wildfly 9.0.1 application server and trying to use force.com java sdk.
Following [javaample-musiclib] (https://github.com/forcedotcom/javasample-musiclib) sample, I updated the file src/main/resources/META-INF/persistence.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.1" xmlns="http://xmlns.jcp.org/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">

    <persistence-unit name="forceDatabase">
        <provider>com.force.sdk.jpa.PersistenceProviderImpl</provider>
        <properties>
            <property name="datanucleus.storeManagerType" value="force" />
            <property name="datanucleus.autoCreateSchema" value="true" />
            <property name="datanucleus.validateTables" value="false" />
            <property name="datanucleus.validateConstraints" value="false" />
            <property name="datanucleus.Optimistic" value="false" />
            <property name="datanucleus.datastoreTransactionDelayOperations" value="true" />
            <property name="datanucleus.jpa.addClassTransformer" value="false" />
            <property name="datanucleus.cache.level2.type" value="none" />
            <property name="datanucleus.detachAllOnCommit" value="true" />
            <property name="datanucleus.copyOnAttach" value="false" />
        </properties>
    </persistence-unit>
</persistence>
```
And my pom.xm file looks like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
											http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.artrunners</groupId>
		<artifactId>ar-web-parent</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../</relativePath>
	</parent>

	<artifactId>ar-web-cli</artifactId>
	<packaging>war</packaging>
	<name>${project.artifactId}</name>
	<description>ArtRunners marketplace web application project</description>


	<properties>
		<force.sdk.version>22.0.9-BETA</force.sdk.version>
	</properties>

	<build>
		<finalName>${project.artifactId}</finalName>
		<plugins>
			<!-- Compiler plugin -->
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<!-- WAR plugin -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>2.6</version>
				<configuration>
					<failOnMissingWebXml>false</failOnMissingWebXml>
				</configuration>
			</plugin>

			<!-- Wildfly deploy plugin -->
			<plugin>
				<groupId>org.wildfly.plugins</groupId>
				<artifactId>wildfly-maven-plugin</artifactId>
				<version>1.1.0.Alpha3</version>
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>deploy</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <name>${project.artifactId}</name>
                    <hostname>${wildfly.hostname}</hostname>
                    <username>${wildfly.username}</username>
                    <password>${wildfly.password}</password>
                    <force>true</force>
                </configuration>
			</plugin>

			<!-- Salesforce plugin -->
			<plugin>
				<groupId>com.force</groupId>
				<artifactId>maven-force-plugin</artifactId>
				<version>22.0.5-BETA</version>
				<configuration>
					<connectionName>connname</connectionName>
					<includes>
						<include>Account</include>
						<include>Contact</include>
						<include>Order</include>
						<include>Quote</include>
						<include>Shipment__c</include>
					</includes>
					<destDir>${basedir}/src/main/java</destDir>
					<packageName>com.artrunners.model.autogen</packageName>
				</configuration>
				<executions>
					<execution>
						<id>generate-force-entities</id>
						<goals>
							<goal>codegen</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.wildfly</groupId>
				<artifactId>wildfly-spec-api</artifactId>
				<version>${version.wildfly}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<!-- Import Wildfly Spec  -->
		<dependency>
			<groupId>org.wildfly</groupId>
			<artifactId>wildfly-spec-api</artifactId>
			<version>${version.wildfly}</version>
			<type>pom</type>
			<scope>provided</scope>
		</dependency>

        <dependency>
            <groupId>org.jboss.spec.javax.servlet</groupId>
            <artifactId>jboss-servlet-api_3.1_spec</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.spec.javax.ws.rs</groupId>
            <artifactId>jboss-jaxrs-api_2.0_spec</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.enterprise</groupId>
            <artifactId>cdi-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>jsr250-api</artifactId>
            <version>1.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.hibernate.javax.persistence</groupId>
            <artifactId>hibernate-jpa-2.1-api</artifactId>
            <scope>provided</scope>
        </dependency>

		<!-- Import Resteasy client  -->
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-client</artifactId>
			<scope>provided</scope>
		</dependency>


		<!-- Salesforce Database.com -->
		<dependency>
			<groupId>com.force.sdk</groupId>
			<artifactId>force-jpa</artifactId>
			<version>${force.sdk.version}</version>
		</dependency>
		<dependency>
			<groupId>org.datanucleus</groupId>
			<artifactId>datanucleus-core</artifactId>
			<version>2.2.3</version>
		</dependency>
		<dependency>
			<groupId>org.datanucleus</groupId>
			<artifactId>datanucleus-enhancer</artifactId>
			<version>2.1.0-release</version>
		</dependency>
		<dependency>
			<groupId>org.datanucleus</groupId>
			<artifactId>datanucleus-jpa</artifactId>
			<version>2.1.7</version>
		</dependency>
		<dependency>
			<groupId>javax.jdo</groupId>
			<artifactId>jdo2-api</artifactId>
			<version>2.3-eb</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.6.1</version>
		</dependency>

		<!-- JUnit -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${version.junit}</version>
			<scope>test</scope>
		</dependency>

	</dependencies>

</project>

```

Since datanucleus-jpa is an OSGI bundle and Wildfly is not OSGI container, I followed datanucleus guidelines and explicitly defined the persistence provider in file src/main/resources/META-INF/services/javax.persistence.spi.PersistenceProvider:
```text
org.datanucleus.jpa.PersistenceProviderImpl
```

When running the application server, it fails to load datanucleus, here is the error log:
```log
13:31:13,983 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 10) MSC000001: Failed to start service jboss.persistenceunit."ar-web-cli.war#forceDatabase": org.jboss.msc.service.StartException in service jboss.persistenceunit."ar-web-cli.war#forceDatabase": javax.jdo.JDOFatalInternalException: Unexpected exception caught.
NestedThrowables:
java.lang.reflect.InvocationTargetException
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:172)
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:117)
	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:665)
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:182)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: javax.jdo.JDOFatalInternalException: Unexpected exception caught.
NestedThrowables:
java.lang.reflect.InvocationTargetException
	at javax.jdo.JDOHelper.invokeGetPersistenceManagerFactoryOnImplementation(JDOHelper.java:1186)
	at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:803)
	at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:698)
	at org.datanucleus.jpa.EntityManagerFactoryImpl.initialisePMF(EntityManagerFactoryImpl.java:592)
	at org.datanucleus.jpa.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:282)
	at com.force.sdk.jpa.ForceEntityManagerFactory.<init>(ForceEntityManagerFactory.java:53)
	at com.force.sdk.jpa.PersistenceProviderImpl.createContainerEntityManagerFactory(PersistenceProviderImpl.java:59)
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.createContainerEntityManagerFactory(PersistenceUnitServiceImpl.java:318)
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl.access$1100(PersistenceUnitServiceImpl.java:67)
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:167)
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at javax.jdo.JDOHelper$16.run(JDOHelper.java:1956)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.jdo.JDOHelper.invoke(JDOHelper.java:1951)
	at javax.jdo.JDOHelper.invokeGetPersistenceManagerFactoryOnImplementation(JDOHelper.java:1159)
	... 16 more
Caused by: org.datanucleus.exceptions.NucleusUserException: Persistence process has been specified to use a ClassLoaderResolver of name "" yet this has not been found by the DataNucleus plugin mechanism. Please check your CLASSPATH and plugin specification.
	at org.datanucleus.OMFContext.getClassLoaderResolver(OMFContext.java:327)
	at org.datanucleus.OMFContext.<init>(OMFContext.java:181)
	at org.datanucleus.OMFContext.<init>(OMFContext.java:149)
	at org.datanucleus.ObjectManagerFactoryImpl.initialiseOMFContext(ObjectManagerFactoryImpl.java:137)
	at org.datanucleus.jdo.JDOPersistenceManagerFactory.initialiseProperties(JDOPersistenceManagerFactory.java:370)
	at org.datanucleus.jdo.JDOPersistenceManagerFactory.<init>(JDOPersistenceManagerFactory.java:314)
	at com.force.sdk.jdo.ForceJDOPersistenceManagerFactory.<init>(ForceJDOPersistenceManagerFactory.java:64)
	at com.force.sdk.jdo.ForceJDOPersistenceManagerFactory.createPersistenceManagerFactory(ForceJDOPersistenceManagerFactory.java:98)
	at com.force.sdk.jdo.ForceJDOPersistenceManagerFactory.getPersistenceManagerFactory(ForceJDOPersistenceManagerFactory.java:87)
	... 24 more

13:31:13,991 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 3) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "ar-web-cli.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.persistenceunit.\"ar-web-cli.war#forceDatabase\"" => "org.jboss.msc.service.StartException in service jboss.persistenceunit.\"ar-web-cli.war#forceDatabase\": javax.jdo.JDOFatalInternalException: Unexpected exception caught.
NestedThrowables:
java.lang.reflect.InvocationTargetException
    Caused by: javax.jdo.JDOFatalInternalException: Unexpected exception caught.
NestedThrowables:
java.lang.reflect.InvocationTargetException
    Caused by: java.lang.reflect.InvocationTargetException
    Caused by: org.datanucleus.exceptions.NucleusUserException: Persistence process has been specified to use a ClassLoaderResolver of name \"\" yet this has not been found by the DataNucleus plugin mechanism. Please check your CLASSPATH and plugin specification."}}
13:31:13,994 ERROR [org.jboss.as.server] (management-handler-thread - 3) WFLYSRV0021: Deploy of deployment "ar-web-cli.war" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.persistenceunit.\"ar-web-cli.war#forceDatabase\"" => "org.jboss.msc.service.StartException in service jboss.persistenceunit.\"ar-web-cli.war#forceDatabase\": javax.jdo.JDOFatalInternalException: Unexpected exception caught.
NestedThrowables:
java.lang.reflect.InvocationTargetException
    Caused by: javax.jdo.JDOFatalInternalException: Unexpected exception caught.
NestedThrowables:
java.lang.reflect.InvocationTargetException
    Caused by: java.lang.reflect.InvocationTargetException
    Caused by: org.datanucleus.exceptions.NucleusUserException: Persistence process has been specified to use a ClassLoaderResolver of name \"\" yet this has not been found by the DataNucleus plugin mechanism. Please check your CLASSPATH and plugin specification."}}

```

Any ideas how to get datanucleus to work with Wildfly?

**Comment by jesperfj** [comment]
This library is no longer maintained. [wsc](https://github.com/forcedotcom/wsc) is recommended when connecting to Force.com API from Java.
